version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: root
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
